---
- name: "Loading Debian-like specifc variables"
  ansible.builtin.include_vars:
    file: Debian.yml
- name: "Adding APT keyrings directory"
  ansible.builtin.file:
    path: "{{ rocm_apt_keyring_dir }}"
    mode: 075
    owner: root
    group: root
- name: "Adding AMD ROCm apt key"
  ansible.builtin.apt_key:
    url: "https://repo.radeon.com/rocm/rocm.gpg.key"
    keyring: "{{ rocm_apt_repo_key_file }}"
    id: "{{ ROCM_APT_KEY_ID }}"
- name: "Adding AMD ROCm amdgpu repo"
  ansible.builtin.copy:
    dest: "/etc/apt/sources.list.d/amdgpu.list"
    content: |
      deb [arch=amd64 signed-by={{ rocm_apt_repo_key_file }} ] https://repo.radeon.com/amdgpu/{{ rocm_version }}/ubuntu jammy main
    mode: "644"
    owner: "root"
    group: "root"
  when: rocm_kernel_driver_install == true
- name: "Adding AMD ROCm software repo"
  ansible.builtin.copy:
    dest: "/etc/apt/sources.list.d/rocm.list"
    content: |
      deb [arch=amd64 signed-by={{ rocm_apt_repo_key_file }} ] https://repo.radeon.com/rocm/apt/{{ rocm_version }} jammy main
    mode: "644"
    owner: "root"
    group: "root"
  when: (ansible_lsb.codename is defined) and ("ansible_lsb.codename in lookup('vars','ubuntu_22_04_codenames')")
- name: "Setting Priorities to ROCm repo"
  ansible.builtin.copy:
    dest: "/etc/apt/preferences.d/rocm-pin-600"
    content: |
      Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600
- name: "Installing hwe kernel and amdgpu driver"
  ansible.builtin.apt:
    name:
      - amdgpu-dkms
  when: rocm_kernel_driver_install == true
- name: "Installed dependencies"
  ansible.builtin.apt:
    name:
      - python3
      - python3-venv
      - google-perftools
      - git
      - rocm-hip-libraries
    state: latest
    update_cache: true
